const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'locales');

const newKeys = {
  uk: {
    "common.error": "Помилка",
    "songs.add.error_title_req": "Введіть назву пісні",
    "songs.add.error_cat_req": "Введіть назву нової категорії",
    "songs.add.error_cond_req": "Введіть ім'я диригента",
    "songs.add.error_adding": "Помилка додавання. Спробуйте ще раз.",
    "songs.add.error_deleting": "Помилка видалення",
    "songs.add.new_song": "Нова пісня",
    "songs.add.title_label": "Назва пісні *",
    "songs.add.title_placeholder": "Введіть назву...",
    "songs.add.category_label": "Категорія (Тематика)",
    "songs.add.category_placeholder": "Оберіть категорію...",
    "songs.add.custom_category": "Своя категорія...",
    "songs.add.category_name": "Назва категорії",
    "songs.add.back_to_list": "Назад до списку",
    "songs.add.conductor_label": "Диригент *",
    "songs.add.conductor_placeholder": "Оберіть диригента...",
    "songs.add.other": "Інший...",
    "songs.add.conductor_name": "Ім'я диригента",
    "songs.add.pianist_label": "Піаніст",
    "songs.add.pianist_placeholder": "Оберіть піаніста (опціонально)...",
    "songs.add.no_pianist": "Без піаніста",
    "songs.add.other_pianist": "Інший піаніст...",
    "songs.add.pianist_name": "Ім'я піаніста",
    "songs.add.pdf_label": "PDF Файли (опціонально)",
    "songs.add.part_prompt": "Назва партії (напр. Сопрано, Альт):",
    "songs.add.main_part": "Головна",
    "songs.add.another_file": "Ще один файл",
    "songs.add.upload_pdf": "Завантажити PDF",
    "songs.add.find_in_archive": "Знайти в Архіві МХО",
    "songs.add.adding": "Додавання...",
    "songs.add.add_song": "Додати пісню",
    "songs.add.delete_conductor_title": "Видалити диригента?",
    "songs.add.delete_confirm": "Ви дійсно хочете видалити \"{{name}}\" зі списку?",
    "songs.add.delete_pianist_title": "Видалити піаніста?",
    "songs.add.delete": "Видалити"
  },
  en: {
    "common.error": "Error",
    "songs.add.error_title_req": "Enter song title",
    "songs.add.error_cat_req": "Enter new category name",
    "songs.add.error_cond_req": "Enter conductor's name",
    "songs.add.error_adding": "Error adding. Please try again.",
    "songs.add.error_deleting": "Error deleting",
    "songs.add.new_song": "New song",
    "songs.add.title_label": "Song title *",
    "songs.add.title_placeholder": "Enter title...",
    "songs.add.category_label": "Category (Theme)",
    "songs.add.category_placeholder": "Select category...",
    "songs.add.custom_category": "Custom category...",
    "songs.add.category_name": "Category name",
    "songs.add.back_to_list": "Back to list",
    "songs.add.conductor_label": "Conductor *",
    "songs.add.conductor_placeholder": "Select conductor...",
    "songs.add.other": "Other...",
    "songs.add.conductor_name": "Conductor's name",
    "songs.add.pianist_label": "Pianist",
    "songs.add.pianist_placeholder": "Select pianist (optional)...",
    "songs.add.no_pianist": "No pianist",
    "songs.add.other_pianist": "Other pianist...",
    "songs.add.pianist_name": "Pianist's name",
    "songs.add.pdf_label": "PDF Files (optional)",
    "songs.add.part_prompt": "Part name (e.g. Soprano, Alto):",
    "songs.add.main_part": "Main",
    "songs.add.another_file": "Another file",
    "songs.add.upload_pdf": "Upload PDF",
    "songs.add.find_in_archive": "Find in MHO Archive",
    "songs.add.adding": "Adding...",
    "songs.add.add_song": "Add song",
    "songs.add.delete_conductor_title": "Delete conductor?",
    "songs.add.delete_confirm": "Are you sure you want to delete \"{{name}}\" from the list?",
    "songs.add.delete_pianist_title": "Delete pianist?",
    "songs.add.delete": "Delete"
  },
  ru: {
    "common.error": "Ошибка",
    "songs.add.error_title_req": "Введите название песни",
    "songs.add.error_cat_req": "Введите название новой категории",
    "songs.add.error_cond_req": "Введите имя дирижера",
    "songs.add.error_adding": "Ошибка добавления. Попробуйте еще раз.",
    "songs.add.error_deleting": "Ошибка удаления",
    "songs.add.new_song": "Новая песня",
    "songs.add.title_label": "Название песни *",
    "songs.add.title_placeholder": "Введите название...",
    "songs.add.category_label": "Категория (Тематика)",
    "songs.add.category_placeholder": "Выберите категорию...",
    "songs.add.custom_category": "Своя категория...",
    "songs.add.category_name": "Название категории",
    "songs.add.back_to_list": "Назад к списку",
    "songs.add.conductor_label": "Дирижер *",
    "songs.add.conductor_placeholder": "Выберите дирижера...",
    "songs.add.other": "Другой...",
    "songs.add.conductor_name": "Имя дирижера",
    "songs.add.pianist_label": "Пианист",
    "songs.add.pianist_placeholder": "Выберите пианиста (опционально)...",
    "songs.add.no_pianist": "Без пианиста",
    "songs.add.other_pianist": "Другой пианист...",
    "songs.add.pianist_name": "Имя пианиста",
    "songs.add.pdf_label": "PDF Файлы (опционально)",
    "songs.add.part_prompt": "Название партии (напр. Сопрано, Альт):",
    "songs.add.main_part": "Главная",
    "songs.add.another_file": "Еще один файл",
    "songs.add.upload_pdf": "Загрузить PDF",
    "songs.add.find_in_archive": "Найти в Архиве МХО",
    "songs.add.adding": "Добавление...",
    "songs.add.add_song": "Добавить песню",
    "songs.add.delete_conductor_title": "Удалить дирижера?",
    "songs.add.delete_confirm": "Вы действительно хотите удалить \"{{name}}\" из списка?",
    "songs.add.delete_pianist_title": "Удалить пианиста?",
    "songs.add.delete": "Удалить"
  },
  de: {
    "common.error": "Fehler",
    "songs.add.error_title_req": "Bitte geben Sie den Liedtitel ein",
    "songs.add.error_cat_req": "Bitte geben Sie den neuen Kategorienamen ein",
    "songs.add.error_cond_req": "Bitte geben Sie den Namen des Dirigenten ein",
    "songs.add.error_adding": "Fehler beim Hinzufügen. Bitte versuchen Sie es erneut.",
    "songs.add.error_deleting": "Fehler beim Löschen",
    "songs.add.new_song": "Neues Lied",
    "songs.add.title_label": "Liedtitel *",
    "songs.add.title_placeholder": "Titel eingeben...",
    "songs.add.category_label": "Kategorie (Thema)",
    "songs.add.category_placeholder": "Kategorie auswählen...",
    "songs.add.custom_category": "Benutzerdefinierte Kategorie...",
    "songs.add.category_name": "Kategoriename",
    "songs.add.back_to_list": "Zurück zur Liste",
    "songs.add.conductor_label": "Dirigent *",
    "songs.add.conductor_placeholder": "Dirigent auswählen...",
    "songs.add.other": "Andere...",
    "songs.add.conductor_name": "Name des Dirigenten",
    "songs.add.pianist_label": "Pianist",
    "songs.add.pianist_placeholder": "Pianist auswählen (optional)...",
    "songs.add.no_pianist": "Kein Pianist",
    "songs.add.other_pianist": "Anderer Pianist...",
    "songs.add.pianist_name": "Name des Pianisten",
    "songs.add.pdf_label": "PDF-Dateien (optional)",
    "songs.add.part_prompt": "Partitur-Name (z.B. Sopran, Alt):",
    "songs.add.main_part": "Hauptstimme",
    "songs.add.another_file": "Weitere Datei",
    "songs.add.upload_pdf": "PDF hochladen",
    "songs.add.find_in_archive": "Im MHO-Archiv finden",
    "songs.add.adding": "Hinzufügen...",
    "songs.add.add_song": "Lied hinzufügen",
    "songs.add.delete_conductor_title": "Dirigent löschen?",
    "songs.add.delete_confirm": "Sind Sie sicher, dass Sie \"{{name}}\" aus der Liste löschen möchten?",
    "songs.add.delete_pianist_title": "Pianist löschen?",
    "songs.add.delete": "Löschen"
  }
};

for (const lang of ['uk', 'en', 'ru', 'de']) {
  const file = path.join(localesDir, `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  const merged = { ...data, ...newKeys[lang] };
  fs.writeFileSync(file, JSON.stringify(merged, null, 2) + '\n');
  console.log(`Updated ${lang}.json`);
}
