const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, 'locales');

const newKeys = {
  uk: {
    "songs.list.search_placeholder": "Пошук пісень, регентів...",
    "songs.list.filter_all": "Всі",
    "songs.list.lang_ukr": "🇺🇦 Українська",
    "songs.list.lang_rus": "🇷🇺 Російська",
    "songs.list.lang_eng": "🌍 Англійська",
    "songs.list.main_part": "Головна",
    "songs.list.song": "Пісня",
    "songs.list.already_exists": "вже існує в репертуарі",
    "songs.list.error_title": "Помилка",
    "songs.list.pdf_error": "Пісню створено, але PDF не завантажився.",
    "songs.list.duplicate_title": "Така пісня вже є",
    "songs.list.duplicate_confirm": "вже існує в репертуарі. Ви впевнені, що хочете додати її ще раз?",
    "songs.list.add_btn": "Додати",
    "songs.list.cancel_btn": "Скасувати",
    "songs.list.error_archive_add": "Помилка додавання з архіву",
    "songs.list.success_save": "Зміни збережено",
    "songs.list.error_update": "Помилка оновлення",
    "songs.list.moved_to_trash": "Пісню переміщено до кошика",
    "songs.list.undo_btn": "Скасувати",
    "songs.list.error_delete": "Помилка при видаленні",
    "songs.list.tab_repertoire": "Репертуар",
    "songs.list.tab_archive": "Архів МХО",
    "songs.list.added_from_archive": "додано до репертуару",
    "songs.list.songs_count_plural": "пісень",
    "songs.list.songs_count_single": "пісня",
    "songs.list.trash_tooltip": "Кошик",
    "songs.list.search_title": "Пошук",
    "songs.list.search_placeholder2": "Назва пісні, диригент...",
    "songs.list.empty_search": "Нічого не знайдено",
    "songs.list.start_typing": "Почніть вводити назву пісні",
    "songs.list.col_name": "Назва",
    "songs.list.col_category": "Категорія",
    "songs.list.col_conductor": "Диригент",
    "songs.list.more_info": "Детальніше",
    "songs.list.archive_search_title": "Знайти в архіві",
    "songs.list.delete_title": "Видалити пісню?",
    "songs.list.delete_desc": "Цю пісню буде видалено з репертуару назавжди.",
    "songs.list.delete_btn": "Видалити",
    "songs.list.added_title": "Пісню додано!",
    "songs.list.added_desc": "Пісню успішно додано до репертуару. Відкрити її зараз?",
    "songs.list.open_btn": "Відкрити",
    "songs.list.add_song_tooltip": "Додати пісню",
    "songs.list.not_found": "Пісень не знайдено"
  },
  en: {
    "songs.list.search_placeholder": "Search songs, conductors...",
    "songs.list.filter_all": "All",
    "songs.list.lang_ukr": "🇺🇦 Ukrainian",
    "songs.list.lang_rus": "🇷🇺 Russian",
    "songs.list.lang_eng": "🌍 English",
    "songs.list.main_part": "Main",
    "songs.list.song": "Song",
    "songs.list.already_exists": "already exists in repertoire",
    "songs.list.error_title": "Error",
    "songs.list.pdf_error": "Song created, but PDF failed to upload.",
    "songs.list.duplicate_title": "Song already exists",
    "songs.list.duplicate_confirm": "already exists in repertoire. Are you sure you want to add it again?",
    "songs.list.add_btn": "Add",
    "songs.list.cancel_btn": "Cancel",
    "songs.list.error_archive_add": "Error adding from archive",
    "songs.list.success_save": "Changes saved",
    "songs.list.error_update": "Error updating",
    "songs.list.moved_to_trash": "Song moved to trash",
    "songs.list.undo_btn": "Undo",
    "songs.list.error_delete": "Error deleting",
    "songs.list.tab_repertoire": "Repertoire",
    "songs.list.tab_archive": "Choir Archive",
    "songs.list.added_from_archive": "added to repertoire",
    "songs.list.songs_count_plural": "songs",
    "songs.list.songs_count_single": "song",
    "songs.list.trash_tooltip": "Trash",
    "songs.list.search_title": "Search",
    "songs.list.search_placeholder2": "Song title, conductor...",
    "songs.list.empty_search": "Nothing found",
    "songs.list.start_typing": "Start typing a song title",
    "songs.list.col_name": "Title",
    "songs.list.col_category": "Category",
    "songs.list.col_conductor": "Conductor",
    "songs.list.more_info": "More options",
    "songs.list.archive_search_title": "Search in Archive",
    "songs.list.delete_title": "Delete song?",
    "songs.list.delete_desc": "This song will be permanently removed from the repertoire.",
    "songs.list.delete_btn": "Delete",
    "songs.list.added_title": "Song added!",
    "songs.list.added_desc": "Song successfully added to repertoire. Open it now?",
    "songs.list.open_btn": "Open",
    "songs.list.add_song_tooltip": "Add song",
    "songs.list.not_found": "No songs found"
  },
  ru: {
    "songs.list.search_placeholder": "Поиск песен, регентов...",
    "songs.list.filter_all": "Все",
    "songs.list.lang_ukr": "🇺🇦 Украинский",
    "songs.list.lang_rus": "🇷🇺 Русский",
    "songs.list.lang_eng": "🌍 Английский",
    "songs.list.main_part": "Главная",
    "songs.list.song": "Песня",
    "songs.list.already_exists": "уже есть в репертуаре",
    "songs.list.error_title": "Ошибка",
    "songs.list.pdf_error": "Песня создана, но PDF не загрузился.",
    "songs.list.duplicate_title": "Такая песня уже есть",
    "songs.list.duplicate_confirm": "уже есть в репертуаре. Вы уверены, что хотите добавить ее еще раз?",
    "songs.list.add_btn": "Добавить",
    "songs.list.cancel_btn": "Отмена",
    "songs.list.error_archive_add": "Ошибка добавления из архива",
    "songs.list.success_save": "Изменения сохранены",
    "songs.list.error_update": "Ошибка обновления",
    "songs.list.moved_to_trash": "Песня перемещена в корзину",
    "songs.list.undo_btn": "Отмена",
    "songs.list.error_delete": "Ошибка при удалении",
    "songs.list.tab_repertoire": "Репертуар",
    "songs.list.tab_archive": "Архив МХО",
    "songs.list.added_from_archive": "добавлена в репертуар",
    "songs.list.songs_count_plural": "песен",
    "songs.list.songs_count_single": "песня",
    "songs.list.trash_tooltip": "Корзина",
    "songs.list.search_title": "Поиск",
    "songs.list.search_placeholder2": "Название песни, дирижер...",
    "songs.list.empty_search": "Ничего не найдено",
    "songs.list.start_typing": "Начните вводить название песни",
    "songs.list.col_name": "Название",
    "songs.list.col_category": "Категория",
    "songs.list.col_conductor": "Дирижер",
    "songs.list.more_info": "Подробнее",
    "songs.list.archive_search_title": "Найти в архиве",
    "songs.list.delete_title": "Удалить песню?",
    "songs.list.delete_desc": "Эта песня будет навсегда удалена из репертуара.",
    "songs.list.delete_btn": "Удалить",
    "songs.list.added_title": "Песня добавлена!",
    "songs.list.added_desc": "Песня успешно добавлена в репертуар. Открыть ее сейчас?",
    "songs.list.open_btn": "Открыть",
    "songs.list.add_song_tooltip": "Добавить песню",
    "songs.list.not_found": "Песни не найдены"
  },
  de: {
    "songs.list.search_placeholder": "Lieder, Chorleiter suchen...",
    "songs.list.filter_all": "Alle",
    "songs.list.lang_ukr": "🇺🇦 Ukrainisch",
    "songs.list.lang_rus": "🇷🇺 Russisch",
    "songs.list.lang_eng": "🌍 Englisch",
    "songs.list.main_part": "Hauptstimme",
    "songs.list.song": "Lied",
    "songs.list.already_exists": "existiert bereits im Repertoire",
    "songs.list.error_title": "Fehler",
    "songs.list.pdf_error": "Lied erstellt, aber PDF-Upload fehlgeschlagen.",
    "songs.list.duplicate_title": "Lied existiert bereits",
    "songs.list.duplicate_confirm": "existiert bereits im Repertoire. Möchten Sie es wirklich erneut hinzufügen?",
    "songs.list.add_btn": "Hinzufügen",
    "songs.list.cancel_btn": "Abbrechen",
    "songs.list.error_archive_add": "Fehler beim Hinzufügen aus dem Archiv",
    "songs.list.success_save": "Änderungen gespeichert",
    "songs.list.error_update": "Fehler beim Aktualisieren",
    "songs.list.moved_to_trash": "Lied in den Papierkorb verschoben",
    "songs.list.undo_btn": "Rückgängig",
    "songs.list.error_delete": "Fehler beim Löschen",
    "songs.list.tab_repertoire": "Repertoire",
    "songs.list.tab_archive": "Chorarchiv",
    "songs.list.added_from_archive": "zum Repertoire hinzugefügt",
    "songs.list.songs_count_plural": "Lieder",
    "songs.list.songs_count_single": "Lied",
    "songs.list.trash_tooltip": "Papierkorb",
    "songs.list.search_title": "Suche",
    "songs.list.search_placeholder2": "Liedtitel, Chorleiter...",
    "songs.list.empty_search": "Nichts gefunden",
    "songs.list.start_typing": "Geben Sie einen Liedtitel ein",
    "songs.list.col_name": "Titel",
    "songs.list.col_category": "Kategorie",
    "songs.list.col_conductor": "Chorleiter",
    "songs.list.more_info": "Mehr Optionen",
    "songs.list.archive_search_title": "Im Archiv suchen",
    "songs.list.delete_title": "Lied löschen?",
    "songs.list.delete_desc": "Dieses Lied wird dauerhaft aus dem Repertoire entfernt.",
    "songs.list.delete_btn": "Löschen",
    "songs.list.added_title": "Lied hinzugefügt!",
    "songs.list.added_desc": "Lied erfolgreich zum Repertoire hinzugefügt. Jetzt öffnen?",
    "songs.list.open_btn": "Öffnen",
    "songs.list.add_song_tooltip": "Lied hinzufügen",
    "songs.list.not_found": "Keine Lieder gefunden"
  }
};

for (const lang of ['uk', 'en', 'ru', 'de']) {
  const file = path.join(localesDir, `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  const merged = { ...data, ...newKeys[lang] };
  fs.writeFileSync(file, JSON.stringify(merged, null, 2) + '\n');
  console.log(`[${lang}] Injected ${Object.keys(newKeys[lang]).length} SongList keys.`);
}
console.log('[DONE]');
process.exit(0);
