const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, 'locales');

const newKeys = {
  uk: {
    "layout.tabs.services": "СЛУЖІННЯ",
    "layout.tabs.songs": "ПІСНІ",
    "layout.tabs.members": "УЧАСНИКИ",
    "layout.account": "Акаунт",
    "layout.add": "Додати",
    "global.voices.all": "Всі",
    "global.voices.soprano": "Сопрано",
    "global.voices.alto": "Альт",
    "global.voices.tenor": "Тенор",
    "global.voices.bass": "Бас",
    "global.roles.head": "Керівник",
    "global.roles.regent": "РЕГЕНТ",
    "global.roles.member": "Учасник",
    "global.me": "Я",
    "services.list.upcoming": "Найближчі служіння",
    "services.list.archive": "Архів",
    "services.list.empty": "Немає запланованих служінь",
    "services.list.create_first": "Створити перше",
    "services.create.tab_service": "Служіння",
    "services.create.tab_rehearsal": "Репетиція",
    "services.create.default_title": "Співанка",
    "services.create.btn_create": "Створити",
    "legal.title_sources": "Джерела та контент",
    "legal.sec_catalog": "Каталог пісень",
    "legal.sec_catalog_desc1": "Каталог пісень у застосунку сформовано на основі відкритих матеріалів, опублікованих Музично-хоровим відділом МСЦ ЄХБ (Міжнародний союз церков євангельських християн-баптистів).",
    "legal.sec_catalog_desc2": "Ці матеріали призначені для вільного використання в церковному служінні та доступні на офіційному сайті організації.",
    "legal.btn_source": "Перейти до джерела",
    "legal.sec_copyright": "Авторські права",
    "legal.sec_copyright_desc1": "Застосунок не є власником музичних творів і не претендує на авторські права. Всі права на оригінальні твори належать їх авторам та правовласникам.",
    "legal.sec_copyright_desc2": "Ми лише надаємо зручний інтерфейс для доступу до матеріалів, які вже є у відкритому доступі.",
    "legal.sec_user_content": "Користувацький контент",
    "legal.sec_user_content_desc1": "Користувачі можуть додавати власні матеріали (ноти, тексти, PDF-файли) для використання в межах свого хору або церковної спільноти.",
    "legal.sec_user_content_desc2": "Завантажений контент зберігається на захищених серверах і доступний лише учасникам відповідного хору.",
    "legal.sec_protection": "Захист даних",
    "legal.sec_protection_desc1": "Ваші дані зашифровані та зберігаються на серверах Google Firebase та Cloudflare з дотриманням стандартів GDPR.",
    "legal.sec_protection_desc2": "Ми не передаємо ваші персональні дані третім сторонам для маркетингових або комерційних цілей.",
    "legal.sec_responsibility": "Відповідальність",
    "legal.sec_responsibility_desc1": "Користувачі несуть відповідальність за контент, який вони додають або використовують у застосунку.",
    "legal.sec_responsibility_desc2": "Завантажуючи матеріали, ви підтверджуєте, що маєте право на їх використання в межах церковного служіння та некомерційних цілей.",
    "legal.sec_legal": "Правова інформація",
    "legal.sec_legal_desc1": "Детальну інформацію про обробку персональних даних можна знайти в нашій Політиці конфіденційності.",
    "legal.privacy_policy": "Політика конфіденційності",
    "legal.terms_of_use": "Умови використання"
  },
  en: {
    "layout.tabs.services": "SERVICES",
    "layout.tabs.songs": "SONGS",
    "layout.tabs.members": "MEMBERS",
    "layout.account": "Account",
    "layout.add": "Add",
    "global.voices.all": "All",
    "global.voices.soprano": "Soprano",
    "global.voices.alto": "Alto",
    "global.voices.tenor": "Tenor",
    "global.voices.bass": "Bass",
    "global.roles.head": "Head",
    "global.roles.regent": "CONDUCTOR",
    "global.roles.member": "Member",
    "global.me": "Me",
    "services.list.upcoming": "Upcoming Services",
    "services.list.archive": "Archive",
    "services.list.empty": "No scheduled services",
    "services.list.create_first": "Create the first one",
    "services.create.tab_service": "Service",
    "services.create.tab_rehearsal": "Rehearsal",
    "services.create.default_title": "Warmup",
    "services.create.btn_create": "Create",
    "legal.title_sources": "Sources & Content",
    "legal.sec_catalog": "Song Catalog",
    "legal.sec_catalog_desc1": "The app's song catalog is based on open materials published by the Music and Choir Department of the IUCECB (International Union of Churches of Evangelical Christian Baptists).",
    "legal.sec_catalog_desc2": "These materials are intended for free use in church services and are available on the organization's official website.",
    "legal.btn_source": "Go to source",
    "legal.sec_copyright": "Copyright",
    "legal.sec_copyright_desc1": "The application does not own musical works and claims no copyright. All rights to original works belong to their authors and rights holders.",
    "legal.sec_copyright_desc2": "We only provide a convenient interface to access materials that are already in the public domain.",
    "legal.sec_user_content": "User Content",
    "legal.sec_user_content_desc1": "Users can add their own materials (sheet music, lyrics, PDF files) for use within their choir or church community.",
    "legal.sec_user_content_desc2": "Uploaded content is stored on secure servers and is accessible only to members of the respective choir.",
    "legal.sec_protection": "Data Protection",
    "legal.sec_protection_desc1": "Your data is encrypted and stored on Google Firebase and Cloudflare servers in compliance with GDPR standards.",
    "legal.sec_protection_desc2": "We do not share your personal data with third parties for marketing or commercial purposes.",
    "legal.sec_responsibility": "Responsibility",
    "legal.sec_responsibility_desc1": "Users are responsible for the content they add or use within the application.",
    "legal.sec_responsibility_desc2": "By uploading materials, you confirm that you have the right to use them for church services and non-commercial purposes.",
    "legal.sec_legal": "Legal Information",
    "legal.sec_legal_desc1": "Detailed information regarding personal data processing can be found in our Privacy Policy.",
    "legal.privacy_policy": "Privacy Policy",
    "legal.terms_of_use": "Terms of Use"
  },
  ru: {
    "layout.tabs.services": "СЛУЖЕНИЯ",
    "layout.tabs.songs": "ПЕСНИ",
    "layout.tabs.members": "УЧАСТНИКИ",
    "layout.account": "Аккаунт",
    "layout.add": "Добавить",
    "global.voices.all": "Все",
    "global.voices.soprano": "Сопрано",
    "global.voices.alto": "Альт",
    "global.voices.tenor": "Тенор",
    "global.voices.bass": "Бас",
    "global.roles.head": "Руководитель",
    "global.roles.regent": "РЕГЕНТ",
    "global.roles.member": "Участник",
    "global.me": "Я",
    "services.list.upcoming": "Ближайшие служения",
    "services.list.archive": "Архив",
    "services.list.empty": "Нет запланированных служений",
    "services.list.create_first": "Создать первое",
    "services.create.tab_service": "Служение",
    "services.create.tab_rehearsal": "Спевка",
    "services.create.default_title": "Спевка",
    "services.create.btn_create": "Создать",
    "legal.title_sources": "Источники и контент",
    "legal.sec_catalog": "Каталог песен",
    "legal.sec_catalog_desc1": "Каталог песен в приложении сформирован на основе открытых материалов, опубликованных Музыкально-хоровым отделом МСЦ ЕХБ.",
    "legal.sec_catalog_desc2": "Эти материалы предназначены для свободного использования в церковном служении и доступны на официальном сайте организации.",
    "legal.btn_source": "Перейти к источнику",
    "legal.sec_copyright": "Авторские права",
    "legal.sec_copyright_desc1": "Приложение не является владельцем музыкальных произведений и не претендует на авторские права. Все права принадлежат их авторам и правообладателям.",
    "legal.sec_copyright_desc2": "Мы лишь предоставляем удобный интерфейс для доступа к материалам, которые уже находятся в открытом доступе.",
    "legal.sec_user_content": "Пользовательский контент",
    "legal.sec_user_content_desc1": "Пользователи могут добавлять собственные материалы (ноты, тексты, PDF-файлы) для использования в рамках своего хора или церкви.",
    "legal.sec_user_content_desc2": "Загруженный контент хранится на защищенных серверах и доступен только участникам соответствующего хора.",
    "legal.sec_protection": "Защита данных",
    "legal.sec_protection_desc1": "Ваши данные зашифрованы и хранятся на серверах Google Firebase и Cloudflare с соблюдением стандартов GDPR.",
    "legal.sec_protection_desc2": "Мы не передаем ваши персональные данные третьим лицам для маркетинговых или коммерческих целей.",
    "legal.sec_responsibility": "Ответственность",
    "legal.sec_responsibility_desc1": "Пользователи несут ответственность за контент, который они добавляют или используют в приложении.",
    "legal.sec_responsibility_desc2": "Загружая материалы, вы подтверждаете, что имеете право на их использование в рамках церковного служения и некоммерческих целей.",
    "legal.sec_legal": "Правовая информация",
    "legal.sec_legal_desc1": "Подробную информацию об обработке персональных данных можно найти в нашей Политике конфиденциальности.",
    "legal.privacy_policy": "Политика конфиденциальности",
    "legal.terms_of_use": "Условия использования"
  },
  de: {
    "layout.tabs.services": "GOTTESDIENSTE",
    "layout.tabs.songs": "LIEDER",
    "layout.tabs.members": "MITGLIEDER",
    "layout.account": "Konto",
    "layout.add": "Hinzufügen",
    "global.voices.all": "Alle",
    "global.voices.soprano": "Sopran",
    "global.voices.alto": "Alt",
    "global.voices.tenor": "Tenor",
    "global.voices.bass": "Bass",
    "global.roles.head": "Leiter",
    "global.roles.regent": "DIRIGENT",
    "global.roles.member": "Mitglied",
    "global.me": "Ich",
    "services.list.upcoming": "Kommende Gottesdienste",
    "services.list.archive": "Archiv",
    "services.list.empty": "Keine Gottesdienste geplant",
    "services.list.create_first": "Ersten erstellen",
    "services.create.tab_service": "Gottesdienst",
    "services.create.tab_rehearsal": "Chorprobe",
    "services.create.default_title": "Einsingen",
    "services.create.btn_create": "Erstellen",
    "legal.title_sources": "Quellen & Inhalte",
    "legal.sec_catalog": "Liedkatalog",
    "legal.sec_catalog_desc1": "Der Liedkatalog der App basiert auf offenen Materialien der Musik- und Chorabteilung der IUBE (Internationale Union der Baptisten-Gemeinden).",
    "legal.sec_catalog_desc2": "Diese Materialien sind zur freien Nutzung im Gottesdienst bestimmt und auf der offiziellen Website der Organisation verfügbar.",
    "legal.btn_source": "Zur Quelle",
    "legal.sec_copyright": "Urheberrecht",
    "legal.sec_copyright_desc1": "Die App besitzt keine Musikwerke und erhebt keinen Anspruch auf Urheberrechte. Alle Rechte an Originalwerken liegen bei den Autoren.",
    "legal.sec_copyright_desc2": "Wir bieten lediglich eine bequeme Schnittstelle für den Zugriff auf öffentlich zugängliche Materialien.",
    "legal.sec_user_content": "Benutzerinhalte",
    "legal.sec_user_content_desc1": "Benutzer können eigene Materialien (Noten, Texte, PDFs) für die Verwendung in ihrem Chor hinzufügen.",
    "legal.sec_user_content_desc2": "Hochgeladene Inhalte werden auf sicheren Servern gespeichert und sind nur für Chormitglieder zugänglich.",
    "legal.sec_protection": "Datenschutz",
    "legal.sec_protection_desc1": "Ihre Daten werden verschlüsselt und auf Servern von Google Firebase & Cloudflare nach GDPR-Standards verarbeitet.",
    "legal.sec_protection_desc2": "Wir geben Ihre persönlichen Daten nicht für Marketing- oder kommerzielle Zwecke an Dritte weiter.",
    "legal.sec_responsibility": "Verantwortung",
    "legal.sec_responsibility_desc1": "Benutzer sind für die Inhalte verantwortlich, die sie in der App hinzufügen oder verwenden.",
    "legal.sec_responsibility_desc2": "Durch das Hochladen bestätigen Sie, dass Sie das Recht haben, diese für Gottesdienste und nichtkommerzielle Zwecke zu nutzen.",
    "legal.sec_legal": "Rechtliche Hinweise",
    "legal.sec_legal_desc1": "Detaillierte Informationen zur Verarbeitung personenbezogener Daten finden Sie in unserer Datenschutzerklärung.",
    "legal.privacy_policy": "Datenschutzerklärung",
    "legal.terms_of_use": "Nutzungsbedingungen"
  }
};

for (const lang of ['uk', 'en', 'ru', 'de']) {
  const file = path.join(localesDir, `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  const merged = { ...data, ...newKeys[lang] };
  fs.writeFileSync(file, JSON.stringify(merged, null, 2) + '\n');
  console.log(`[${lang}] Injected ${Object.keys(newKeys[lang]).length} layout keys.`);
}
console.log('[DONE]');
process.exit(0);
