const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, 'locales');

const newKeys = {
  uk: {
    "stats.detailed.title": "Детальна аналітика",
    "stats.detailed.tab.services": "Служіння",
    "stats.detailed.tab.members": "Хористи",
    "stats.detailed.filter.1m": "1 міс",
    "stats.detailed.filter.3m": "3 міс",
    "stats.detailed.filter.6m": "6 міс",
    "stats.detailed.filter.all": "Усі",
    "stats.detailed.best": "Найкраща",
    "stats.detailed.worst": "Найгірша",
    "stats.detailed.trend_label": "Тренд (останні 5 вс попередні 5)",
    "stats.detailed.monthly_avg": "Середня явка по місяцях",
    "stats.detailed.timeline": "Хронологія служінь",
    "stats.detailed.present": "Присутні",
    "stats.detailed.from": "з",
    "stats.detailed.no_services": "У вас ще немає збережених служінь із зазначеною відвідуваністю.",
    "stats.detailed.attendance_by_voice": "Відвідуваність по партіям",
    "stats.detailed.active": "Активні",
    "stats.detailed.at_risk": "Під ризиком",
    "stats.detailed.inactive": "Неактивні",
    "stats.detailed.personal_rating": "Персональний рейтинг",
    "stats.detailed.attended": "Був(-ла) на",
    "stats.detailed.month.jan": "Січ",
    "stats.detailed.month.feb": "Лют",
    "stats.detailed.month.mar": "Бер",
    "stats.detailed.month.apr": "Кві",
    "stats.detailed.month.may": "Тра",
    "stats.detailed.month.jun": "Чер",
    "stats.detailed.month.jul": "Лип",
    "stats.detailed.month.aug": "Сер",
    "stats.detailed.month.sep": "Вер",
    "stats.detailed.month.oct": "Жов",
    "stats.detailed.month.nov": "Лис",
    "stats.detailed.month.dec": "Гру"
  },
  en: {
    "stats.detailed.title": "Detailed Analytics",
    "stats.detailed.tab.services": "Services",
    "stats.detailed.tab.members": "Members",
    "stats.detailed.filter.1m": "1 mo",
    "stats.detailed.filter.3m": "3 mo",
    "stats.detailed.filter.6m": "6 mo",
    "stats.detailed.filter.all": "All",
    "stats.detailed.best": "Best",
    "stats.detailed.worst": "Worst",
    "stats.detailed.trend_label": "Trend (last 5 vs previous 5)",
    "stats.detailed.monthly_avg": "Monthly Average Attendance",
    "stats.detailed.timeline": "Service Timeline",
    "stats.detailed.present": "Present",
    "stats.detailed.from": "of",
    "stats.detailed.no_services": "You don't have any saved services with recorded attendance yet.",
    "stats.detailed.attendance_by_voice": "Attendance by Voice Part",
    "stats.detailed.active": "Active",
    "stats.detailed.at_risk": "At Risk",
    "stats.detailed.inactive": "Inactive",
    "stats.detailed.personal_rating": "Personal Rating",
    "stats.detailed.attended": "Attended",
    "stats.detailed.month.jan": "Jan",
    "stats.detailed.month.feb": "Feb",
    "stats.detailed.month.mar": "Mar",
    "stats.detailed.month.apr": "Apr",
    "stats.detailed.month.may": "May",
    "stats.detailed.month.jun": "Jun",
    "stats.detailed.month.jul": "Jul",
    "stats.detailed.month.aug": "Aug",
    "stats.detailed.month.sep": "Sep",
    "stats.detailed.month.oct": "Oct",
    "stats.detailed.month.nov": "Nov",
    "stats.detailed.month.dec": "Dec"
  },
  ru: {
    "stats.detailed.title": "Подробная аналитика",
    "stats.detailed.tab.services": "Служения",
    "stats.detailed.tab.members": "Хористы",
    "stats.detailed.filter.1m": "1 мес",
    "stats.detailed.filter.3m": "3 мес",
    "stats.detailed.filter.6m": "6 мес",
    "stats.detailed.filter.all": "Все",
    "stats.detailed.best": "Лучшая",
    "stats.detailed.worst": "Худшая",
    "stats.detailed.trend_label": "Тренд (последние 5 vs предыд. 5)",
    "stats.detailed.monthly_avg": "Средняя явка по месяцам",
    "stats.detailed.timeline": "История служений",
    "stats.detailed.present": "Присутствовали",
    "stats.detailed.from": "из",
    "stats.detailed.no_services": "У вас еще нет сохраненных служений с отмеченной посещаемостью.",
    "stats.detailed.attendance_by_voice": "Посещаемость по партиям",
    "stats.detailed.active": "Активные",
    "stats.detailed.at_risk": "В зоне риска",
    "stats.detailed.inactive": "Неактивные",
    "stats.detailed.personal_rating": "Персональный рейтинг",
    "stats.detailed.attended": "Был(а) на",
    "stats.detailed.month.jan": "Янв",
    "stats.detailed.month.feb": "Фев",
    "stats.detailed.month.mar": "Мар",
    "stats.detailed.month.apr": "Апр",
    "stats.detailed.month.may": "Май",
    "stats.detailed.month.jun": "Июн",
    "stats.detailed.month.jul": "Июл",
    "stats.detailed.month.aug": "Авг",
    "stats.detailed.month.sep": "Сен",
    "stats.detailed.month.oct": "Окт",
    "stats.detailed.month.nov": "Ноя",
    "stats.detailed.month.dec": "Дек"
  },
  de: {
    "stats.detailed.title": "Detaillierte Analyse",
    "stats.detailed.tab.services": "Dienste",
    "stats.detailed.tab.members": "Mitglieder",
    "stats.detailed.filter.1m": "1 Mon",
    "stats.detailed.filter.3m": "3 Mon",
    "stats.detailed.filter.6m": "6 Mon",
    "stats.detailed.filter.all": "Alle",
    "stats.detailed.best": "Beste",
    "stats.detailed.worst": "Schlechteste",
    "stats.detailed.trend_label": "Trend (letzte 5 vs vorherige 5)",
    "stats.detailed.monthly_avg": "Monatliche Durchschnittsanwesenheit",
    "stats.detailed.timeline": "Dienst-Chronik",
    "stats.detailed.present": "Anwesend",
    "stats.detailed.from": "von",
    "stats.detailed.no_services": "Sie haben noch keine gespeicherten Dienste mit Anwesenheitserfassung.",
    "stats.detailed.attendance_by_voice": "Anwesenheit nach Stimme",
    "stats.detailed.active": "Aktiv",
    "stats.detailed.at_risk": "Gefährdet",
    "stats.detailed.inactive": "Inaktiv",
    "stats.detailed.personal_rating": "Persönliche Bewertung",
    "stats.detailed.attended": "War bei",
    "stats.detailed.month.jan": "Jan",
    "stats.detailed.month.feb": "Feb",
    "stats.detailed.month.mar": "Mär",
    "stats.detailed.month.apr": "Apr",
    "stats.detailed.month.may": "Mai",
    "stats.detailed.month.jun": "Jun",
    "stats.detailed.month.jul": "Jul",
    "stats.detailed.month.aug": "Aug",
    "stats.detailed.month.sep": "Sep",
    "stats.detailed.month.oct": "Okt",
    "stats.detailed.month.nov": "Nov",
    "stats.detailed.month.dec": "Dez"
  }
};

for (const lang of ['uk', 'en', 'ru', 'de']) {
  const file = path.join(localesDir, `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  const merged = { ...data, ...newKeys[lang] };
  fs.writeFileSync(file, JSON.stringify(merged, null, 2) + '\n');
  console.log(`[${lang}] Injected ${Object.keys(newKeys[lang]).length} detailed stats keys.`);
}
console.log('[DONE]');
process.exit(0);
