import json

en_overrides = {
    "permissions.add_songs": "Add songs",
    "permissions.edit_attendance": "Take attendance",
    "permissions.edit_credits": "Edit conductor/pianist",
    "permissions.view_stats": "View statistics",
    "permissions.manage_services": "Manage services",
    "permissions.notify_members": "Send notifications",
    "manager.error_save": "Save error",
    "manager.error_join": "Join error",
    "manager.error_already_member": "You are already a member of this choir",
    "manager.error_invalid_code": "Invalid code",
    "manager.error_delete_account": "An error occurred while deleting the account",
    "manager.error_leave_choir": "Failed to leave choir",
    "manager.error_merge_members": "Failed to merge members",
    "manager.error_link_user": "Failed to link user",
    "manager.error_already_linked_to_other": "This profile is already linked to another account. Contact the conductor to relink.",
    "manager.error_account_already_linked": "Your account is already linked to another member.",
    "manager.error_link_prefix": "Linking error:",
    "manager.error_create_choir_prefix": "Choir creation error:",
    "manager.error_unknown": "Unknown error",
    "account.logout_warning": "You will need to sign in with Google to log back in.",
    "account.change_photo": "Tap to change photo",
    "account.delete_photo_title": "Delete photo?",
    "account.delete_photo_confirm": "Are you sure you want to delete the choir photo?",
    "account.delete_photo": "Delete photo",
    "common.save_changes": "Save changes",
    "account.leave_choir": "Leave choir",
    "manager.create": "Create",
    "manager.join": "Join",
    "common.back_arrow": "← Back",
    "manager.last_name_optional": "Last Name (optional)",
    "manager.first_name_optional": "First Name (optional)",
    "manager.code_placeholder": "Code (6 chars)",
    "account.claim_found_similar": "We found a similar name in the choir list.",
    "account.claim_link_desc": "Link your account to this profile to save your attendance history and voice part.",
    "account.claim_already_linked_warning": "If your name is marked \"already has account\", contact the conductor to relink.",
    "account.claim_yes": "Yes, that's me",
    "account.claim_no_new": "No, I'm new",
    "account.claim_name_hint": "Optionally, add your name to help conductors identify you. These fields can be skipped.",
    "common.continue": "Continue",
    "account.admin_role": "Admin",
    "common.clear": "Clear",
    "account.cache_1gb": "1 GB",
    "account.cache_500mb": "500 MB",
    "account.cache_50mb": "50 MB",
    "common.days_7": "7 days",
    "common.days_30": "30 days",
    "common.days_90": "90 days",
    "common.day_one": "1 day",
    "account.contact_title": "Send Email",
    "account.contact_msg": "Open mail app to contact support?",
    "common.open": "Open",
    "account.delete_account": "Delete account",
    "service.unknown_song": "Unknown song",
    "service.choir_song_keyword": "choir song",
    "common.at_time": "at",
    "service.print_error_empty_canvas": "HTML2Canvas returned an empty canvas.",
    "service.print_program_prefix": "Program:",
    "service.empty_list": "List is empty",
    "service.empty_rehearsal_hint": "Tap to add songs to the rehearsal",
    "service.empty_songs_hint": "No songs added yet",
    "service.remove_song_suffix": "will be removed from this program.",
    "service.remove_item_suffix": "will be deleted from the program."
}

de_overrides = {
    "permissions.add_songs": "Lieder hinzufügen",
    "permissions.edit_attendance": "Anwesenheit erfassen",
    "permissions.edit_credits": "Dirigent/Pianist bearbeiten",
    "permissions.view_stats": "Statistiken ansehen",
    "permissions.manage_services": "Gottesdienste verwalten",
    "permissions.notify_members": "Benachrichtigungen senden",
    "manager.error_save": "Speicherfehler",
    "manager.error_join": "Beitrittsfehler",
    "manager.error_already_member": "Sie sind bereits Mitglied dieses Chores",
    "manager.error_invalid_code": "Ungültiger Code",
    "manager.error_delete_account": "Fehler beim Löschen des Kontos",
    "manager.error_leave_choir": "Chor verlassen fehlgeschlagen",
    "manager.error_merge_members": "Mitglieder zusammenführen fehlgeschlagen",
    "manager.error_link_user": "Benutzerverknüpfung fehlgeschlagen",
    "manager.error_already_linked_to_other": "Profil ist bereits verknüpft. Dirigenten kontaktieren.",
    "manager.error_account_already_linked": "Ihr Konto ist bereits mit einem anderen Mitglied verknüpft.",
    "manager.error_link_prefix": "Verknüpfungsfehler:",
    "manager.error_create_choir_prefix": "Chor-Erstellungsfehler:",
    "manager.error_unknown": "Unbekannter Fehler",
    "account.logout_warning": "Sie müssen sich erneut mit Google anmelden.",
    "account.change_photo": "Tippen zum Ändern",
    "account.delete_photo_title": "Foto löschen?",
    "account.delete_photo_confirm": "Möchten Sie das Chorfoto wirklich löschen?",
    "account.delete_photo": "Foto löschen",
    "common.save_changes": "Änderungen speichern",
    "account.leave_choir": "Chor verlassen",
    "manager.create": "Erstellen",
    "manager.join": "Beitreten",
    "common.back_arrow": "← Zurück",
    "manager.last_name_optional": "Nachname (optional)",
    "manager.first_name_optional": "Vorname (optional)",
    "manager.code_placeholder": "Code (6 Zeichen)",
    "account.claim_found_similar": "Wir haben einen ähnlichen Namen gefunden.",
    "account.claim_link_desc": "Verknüpfen Sie Ihr Konto, um Ihre Anwesenheit zu speichern.",
    "account.claim_already_linked_warning": "Wenn Ihr Name als verknüpft markiert ist, kontaktieren Sie den Dirigenten.",
    "account.claim_yes": "Ja, das bin ich",
    "account.claim_no_new": "Nein, ich bin neu",
    "account.claim_name_hint": "Fügen Sie Ihren Namen hinzu. Kann übersprungen werden.",
    "common.continue": "Weiter",
    "account.admin_role": "Admin",
    "common.clear": "Leeren",
    "account.cache_1gb": "1 GB",
    "account.cache_500mb": "500 MB",
    "account.cache_50mb": "50 MB",
    "common.days_7": "7 Tage",
    "common.days_30": "30 Tage",
    "common.days_90": "90 Tage",
    "common.day_one": "1 Tag",
    "account.contact_title": "E-Mail senden",
    "account.contact_msg": "Mail-App für Support öffnen?",
    "common.open": "Öffnen",
    "account.delete_account": "Konto löschen",
    "service.unknown_song": "Unbekanntes Lied",
    "service.choir_song_keyword": "Chorlied",
    "common.at_time": "um",
    "service.print_error_empty_canvas": "HTML2Canvas gab leeres Bild zurück.",
    "service.print_program_prefix": "Programm:",
    "service.empty_list": "Liste ist leer",
    "service.empty_rehearsal_hint": "Tippen, um Lieder hinzuzufügen",
    "service.empty_songs_hint": "Noch keine Lieder",
    "service.remove_song_suffix": "wird aus diesem Programm entfernt.",
    "service.remove_item_suffix": "wird aus dem Programm gelöscht."
}

ru_overrides = {
    "permissions.add_songs": "Добавлять песни",
    "permissions.edit_attendance": "Отмечать отсутствующих",
    "permissions.edit_credits": "Указывать дирижера",
    "permissions.view_stats": "Видеть статистику",
    "permissions.manage_services": "Управлять служениями",
    "permissions.notify_members": "Рассылать уведомления",
    "manager.error_save": "Ошибка сохранения",
    "manager.error_join": "Ошибка присоединения",
    "manager.error_already_member": "Вы уже участник хора",
    "manager.error_invalid_code": "Неверный код",
    "manager.error_delete_account": "Ошибка удаления аккаунта",
    "manager.error_leave_choir": "Не удалось покинуть хор",
    "manager.error_merge_members": "Не удалось объединить",
    "manager.error_link_user": "Не удалось привязать",
    "manager.error_already_linked_to_other": "Профиль уже привязан к другому аккаунту.",
    "manager.error_account_already_linked": "Ваш аккаунт уже привязан к другому.",
    "manager.error_link_prefix": "Ошибка привязки:",
    "manager.error_create_choir_prefix": "Ошибка создания хора:",
    "manager.error_unknown": "Неизвестная ошибка",
    "account.logout_warning": "Потребуется снова войти через Google.",
    "account.change_photo": "Нажмите, чтобы изменить",
    "account.delete_photo_title": "Удалить фото?",
    "account.delete_photo_confirm": "Вы уверены, что хотите удалить фото?",
    "account.delete_photo": "Удалить фото",
    "common.save_changes": "Сохранить изменения",
    "account.leave_choir": "Покинуть хор",
    "manager.create": "Создать",
    "manager.join": "Присоединиться",
    "common.back_arrow": "← Назад",
    "manager.last_name_optional": "Фамилия (необязательно)",
    "manager.first_name_optional": "Имя (необязательно)",
    "manager.code_placeholder": "Код (6 символов)",
    "account.claim_found_similar": "Мы нашли похожее имя.",
    "account.claim_link_desc": "Привяжите аккаунт, чтобы сохранить историю.",
    "account.claim_already_linked_warning": "Если имя занято, обратитесь к регенту.",
    "account.claim_yes": "Да, это я",
    "account.claim_no_new": "Нет, я новый",
    "account.claim_name_hint": "Укажите имя для регента. Можно пропустить.",
    "common.continue": "Продолжить",
    "account.admin_role": "Админ",
    "common.clear": "Очистить",
    "account.cache_1gb": "1 ГБ",
    "account.cache_500mb": "500 МБ",
    "account.cache_50mb": "50 МБ",
    "common.days_7": "7 дней",
    "common.days_30": "30 дней",
    "common.days_90": "90 дней",
    "common.day_one": "1 день",
    "account.contact_title": "Написать письмо",
    "account.contact_msg": "Открыть почтовое приложение?",
    "common.open": "Открыть",
    "account.delete_account": "Удалить аккаунт",
    "service.unknown_song": "Неизвестная песня",
    "service.choir_song_keyword": "песня хора",
    "common.at_time": "в",
    "service.print_error_empty_canvas": "HTML2Canvas вернул пустой холст.",
    "service.print_program_prefix": "Программа:",
    "service.empty_list": "Список пуст",
    "service.empty_rehearsal_hint": "Нажмите, чтобы добавить песни",
    "service.empty_songs_hint": "Песен еще нет",
    "service.remove_song_suffix": "будет убрана из программы.",
    "service.remove_item_suffix": "будет удалена из программы."
}

locales = {
    "locales/en.json": en_overrides,
    "locales/de.json": de_overrides,
    "locales/ru.json": ru_overrides
}

for path, overrides in locales.items():
    with open(path, "r") as f:
        data = json.load(f)
    for k, v in overrides.items():
        if k in data:
            data[k] = v
    with open(path, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Translations applied.")
